#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  mtr_Matrix_S1_1, motorLeft,     tmotorMatrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, motorE,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorRight,    tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, motorLifter,   tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{

  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();
	float power = 60;
	float fortyfive = 45;
  waitForStart(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
	motor [motorLeft] = power;
	motor [motorRight] = power;
	nMotorEncoder [motorLeft] = 0;
	nMotorEncoder [motorRight] = 0;
	while (nMotorEncoder [motorLeft] + nMotorEncoder [motorRight] < 150); //Off the ramp
	motor [motorLeft] = -power;
	nMotorEncoder [motorLeft] = 0;
	nMotorEncoder [motorRight] = 0;
	while (nMotorEncoder [motorRight] - nMotorEncoder [motorLeft] < 2*fortyfive); //Turning 90 degrees
	motor [motorLeft] = power;
	nMotorEncoder [motorLeft] = 0;
	nMotorEncoder [motorRight] = 0;
	while (nMotorEncoder [motorLeft] + nMotorEncoder [motorRight] < 200);//Hitting first pole
	motor [motorLeft] = -power;
	motor [motorRight] = -power;
	nMotorEncoder [motorLeft] = 0;
	nMotorEncoder [motorRight] = 0;
	while (nMotorEncoder [motorLeft] + nMotorEncoder [motorRight] > -50); //Reversing
	motor [motorRight] = power;
	nMotorEncoder [motorLeft] = 0;
	nMotorEncoder [motorRight] = 0;
	while (nMotorEncoder [motorRight] - nMotorEncoder [motorLeft] < fortyfive); //Turning towards second pole
	motor [motorLeft] = power;
	nMotorEncoder [motorLeft] = 0;
	nMotorEncoder [motorRight] = 0;
	while (nMotorEncoder [motorLeft] + nMotorEncoder [motorRight] < 100); //Driving to second pole
	motor [motorLeft] = 0;
	motor [motorRight] = 0;
}
