#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S4,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          motorLeft,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(SensorValue(lightSensor) < 50) {
		motor [motorLeft] = -60;
		motor [motorRight] = -60;
	}
while(SensorValue(touchSensor) == 0){
	if(SensorValue(lightSensor) < 50 ){
		motor [motorLeft] = -40;
		motor [motorRight] = -20;
	}else {
	motor [motorLeft] = -20;
	motor [motorRight] = -40;
}
}


}
