#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          motorDoor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorFront,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorBack,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_Matrix_S1_1, motorLeft,     tmotorMatrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_Matrix_S1_2, motorLifter,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_3, motorRight,    tmotorMatrix, openLoop, encoder)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop, encoder)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define button1   0x01
#define button2   0x02
#define button3   0x04
#define button4   0x08
#define button5   0x10
#define button6   0x20
#define button7   0x40
#define button8   0x80
#define button9  0x100
#define button10 0x200
const bool bLogarithmicScale = true;
const bool kMaximumPowerLevel = 100;  // Adjust to set max power level to be used.
int scaleJoystick(int &nJoy1, int nMaxValue = kMaximumPowerLevel)
{
	//
	// This function scales the joystick settings to the appropriate range for
	// controlling a NXT motor.
	//
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings.
	//
	static const int nLogScale[17] =
	{
		  0,   5,   9,   10,
		 12,  15,  18,  24,
		 30,  36,  43,  50,
		 60,  72,  85, 100,
		100
	};
	int nScaled;

	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
	  nScaled /= 8;
	  if (nScaled >= 0)
	    nScaled = nLogScale[nScaled];
	  else
	    nScaled = - nLogScale[ - nScaled];
  }
	nScaled *= nMaxValue;
	nScaled /= 100;
  return nScaled;
}
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
  	float x = joystick.joy1_x1;
  	float y = joystick.joy1_y1;
  	motor[motorLeft] = y + x; // + x means that the left motor is going forward, causing it to go right
  	motor[motorRight] = y - x;
  	/*if (joystick.joy1_Buttons & button1){
  		motor[motorFront] = 100;
  	} else if(joystick.joy1_Buttons & button4){
  	  motor[motorFront] = -60;
  	} else {
  	  motor [motorFront] = 0;
  	}
  	if (joystick.joy1_Buttons & button1){
  		motor[motorBack] = 100;
  	} else if(joystick.joy1_Buttons & button4){
  	  motor[motorBack] = -60;
  	} else {
  	  motor [motorBack] = 0;
  	}
  	if (joystick.joy1_Buttons & button2){
  		motor[motorDoor] = 100;
  	} else if(joystick.joy1_Buttons & button3){
  	  motor[motorDoor] = -60;
  	} else {
  	  motor [motorDoor] = 0;
  	}*/
  	/*if (joystick.joy1_Buttons & button2){
			nMotorEncoderTarget[motorCube] = 0;
		}
		if (joystick.joy1_Buttons & button2){
			nMotorEncoderTarget[motorCube] = 90;
		}*/
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.
  }
}
